---
- name: Test F5 Connectivity
  hosts: lb
  gather_facts: no
  tasks:
    - name: Ensure F5 connectivity
      bigip_device_info:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          validate_certs: no
      delegate_to: localhost
