---
- name: Configure BIG-IP VIP, Pool, and Members
  hosts: localhost
  gather_facts: no
  vars:
    f5_host: "192.168.0.108"  # F5 BIG-IP IP address
    f5_user: "admin"          # F5 BIG-IP username
    f5_password: "W32sobig"  # F5 BIG-IP password
    vip_name: "osm_443_vip"         # Virtual server name
    pool_name: "osm_443_pool"       # Pool name
    pool_members:
      - "192.168.1.10"         # Server 1
      - "192.168.1.11"         # Server 2
    lb_method: "round_robin"   # Load balancing method for pool
    vip_ip: "10.1.1.100"       # VIP IP address

  tasks:
    - name: Create or update BIG-IP pool
      f5networks.f5_bigip.bigip_pool:
        name: "{{ pool_name }}"
        partition: Common
        lb_method: "{{ lb_method }}"
        servers: "{{ pool_members }}"
        provider:
          server: "{{ f5_host }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          validate_certs: no

    - name: Create or update BIG-IP VIP (Virtual Server)
      f5networks.f5_bigip.bigip_virtual_server:
        name: "{{ vip_name }}"
        partition: Common
        destination: "{{ vip_ip }}:80"  # VIP IP and port
        mask: "255.255.255.0"           # Subnet mask
        pool: "{{ pool_name }}"          # Pool to associate with VIP
        profile:
          - http
        provider:
          server: "{{ f5_host }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          validate_certs: no

    - name: Add members to the BIG-IP pool (if not already added)
      f5networks.f5_bigip.bigip_pool_member:
        name: "{{ pool_name }}"
        state: present
        server: "{{ item }}"
        port: 80
        provider:
          server: "{{ f5_host }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          validate_certs: no
      loop: "{{ pool_members }}"
