---
- name: Create F5 VIP, Pool, and Attach Pool to VIP
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Create the Pool
      f5networks.f5_modules.bigip_pool:
        server: "{{ f5_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: no
        name: my_pool
        state: present
        lb_method: round-robin
        monitor: http
      register: pool

    - name: Add Pool Members to the Pool
      f5networks.f5_modules.bigip_pool_member:
        server: "{{ f5_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: no
        pool: "{{ pool.name }}"
        state: present
        name: "{{ item.name }}"
        address: "{{ item.address }}"
        port: "{{ item.port }}"
      loop:
        - { name: "member1", address: "192.168.1.10", port: 80 }
        - { name: "member2", address: "192.168.1.11", port: 80 }

    - name: Create a Virtual Server (VIP)
      f5networks.f5_modules.bigip_virtual_server:
        server: "{{ f5_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: no
        name: my_vip
        state: present
        destination: "192.168.1.100:80"
        ip_protocol: tcp
        pool: "{{ pool.name }}"
        profiles:
          - http
          - tcp
      register: vip

    - name: Verify VIP and Pool Configuration
      debug:
        msg:
          - "Pool created: {{ pool }}"
          - "VIP created: {{ vip }}"
